import type { ExperienceItem, Location } from '@/features/experiences/types'

// Dummy locations for autocomplete
export const DUMMY_LOCATIONS: Location[] = [
  { id: '1', name: 'Dublin, Ireland', coordinates: { lat: 53.3498, lng: -6.2603 } },
  { id: '2', name: 'London, UK', coordinates: { lat: 51.5074, lng: -0.1278 } },
  { id: '3', name: 'Paris, France', coordinates: { lat: 48.8566, lng: 2.3522 } },
  { id: '4', name: 'Barcelona, Spain', coordinates: { lat: 41.3851, lng: 2.1734 } },
  { id: '5', name: 'Rome, Italy', coordinates: { lat: 41.9028, lng: 12.4964 } },
  { id: '6', name: 'Amsterdam, Netherlands', coordinates: { lat: 52.3676, lng: 4.9041 } },
  { id: '7', name: 'Berlin, Germany', coordinates: { lat: 52.52, lng: 13.405 } },
  { id: '8', name: 'Madrid, Spain', coordinates: { lat: 40.4168, lng: -3.7038 } },
  { id: '9', name: 'Lisbon, Portugal', coordinates: { lat: 38.7223, lng: -9.1393 } },
  { id: '10', name: 'Athens, Greece', coordinates: { lat: 37.9838, lng: 23.7275 } },
  { id: '11', name: 'Prague, Czech Republic', coordinates: { lat: 50.0755, lng: 14.4378 } },
  { id: '12', name: 'Vienna, Austria', coordinates: { lat: 48.2082, lng: 16.3738 } },
  { id: '13', name: 'Budapest, Hungary', coordinates: { lat: 47.4979, lng: 19.0402 } },
  { id: '14', name: 'Copenhagen, Denmark', coordinates: { lat: 55.6761, lng: 12.5683 } },
  { id: '15', name: 'Stockholm, Sweden', coordinates: { lat: 59.3293, lng: 18.0686 } },
]

// Helper to generate dates in the next 60 days
const getRandomDate = (daysFromNow: number): Date => {
  const date = new Date()
  date.setDate(date.getDate() + daysFromNow)
  return date
}

// Dummy dining experiences
export const DUMMY_EXPERIENCES: ExperienceItem[] = [
  {
    id: '1',
    name: 'Authentic Italian Family Dinner',
    description:
      'Join our family for a traditional Italian meal prepared with recipes passed down through generations. Experience true Italian hospitality in our cozy home.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h1',
      name: 'Maria Rossi',
      avatar: '/images/hosts/maria.jpg',
      verified: true,
      languages: ['English', 'Italian'],
    },
    cuisine: 'Italian',
    cuisineIcon: '🍝',
    menu_description: '3-course homemade pasta dinner with wine pairing',
    dietary_info: ['Vegetarian option available', 'Gluten-free pasta available'],
    event_date: getRandomDate(5),
    event_time: '7:00 PM',
    event_remain_spots: 5,
    max_guests: 8,
    duration: '2.5 hours',
    price: 45,
    currency: 'EUR',
    includes: ['3 courses', 'Wine pairing', 'Dessert', 'Coffee'],
    rating: 4.9,
    reviews: 127,
    featured: true,
    image: '/images/experiences/italian-pasta.jpg',
    images: [
      '/images/experiences/italian-1.jpg',
      '/images/experiences/italian-2.jpg',
      '/images/experiences/italian-3.jpg',
    ],
    tags: ['Family-friendly', 'Wine pairing', 'Traditional'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '2',
    name: 'Greek Meze Feast',
    description:
      'Experience the warmth of Greek hospitality with an authentic meze feast featuring traditional dishes from our village in Crete.',
    location: 'London, UK',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    host: {
      id: 'h2',
      name: 'Nikos Papadopoulos',
      avatar: '/images/hosts/nikos.jpg',
      verified: true,
      languages: ['English', 'Greek'],
    },
    cuisine: 'Greek',
    cuisineIcon: '🫒',
    menu_description: 'Traditional meze platter with homemade tzatziki and fresh pita',
    dietary_info: ['Vegetarian options', 'Vegan options available'],
    event_date: getRandomDate(8),
    event_time: '6:30 PM',
    event_remain_spots: 3,
    max_guests: 6,
    duration: '3 hours',
    price: 38,
    currency: 'EUR',
    includes: ['Multiple meze dishes', 'Greek wine', 'Dessert', 'Ouzo tasting'],
    rating: 4.8,
    reviews: 94,
    featured: false,
    image: '/images/experiences/restaurant-dining.jpg',
    images: ['/images/experiences/greek-1.jpg', '/images/experiences/greek-2.jpg'],
    tags: ['Vegetarian-friendly', 'Traditional', 'Mediterranean'],
    instant_book: false,
    isFavorited: false,
  },
  {
    id: '3',
    name: 'Indian Home Cooking Experience',
    description:
      'Learn the secrets of authentic North Indian cuisine in a hands-on experience, then enjoy the meal you helped prepare.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h3',
      name: 'Priya Sharma',
      avatar: '/images/hosts/priya.jpg',
      verified: true,
      languages: ['English', 'Hindi'],
    },
    cuisine: 'Indian',
    cuisineIcon: '🍛',
    menu_description: 'Butter chicken, dal makhani, naan, and authentic desserts',
    dietary_info: ['Vegetarian options', 'Vegan options', 'Spice level adjustable'],
    event_date: getRandomDate(12),
    event_time: '6:00 PM',
    event_remain_spots: 6,
    max_guests: 10,
    duration: '3.5 hours',
    price: 42,
    currency: 'EUR',
    includes: ['Full meal', 'Chai tea', 'Recipe booklet', 'Spice kit to take home'],
    rating: 4.95,
    reviews: 156,
    featured: true,
    image: '/images/experiences/restaurant-dining.jpg',
    images: [
      '/images/experiences/indian-1.jpg',
      '/images/experiences/indian-2.jpg',
      '/images/experiences/indian-3.jpg',
    ],
    tags: ['Hands-on', 'Family-friendly', 'Vegetarian-friendly'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '4',
    name: 'Japanese Sushi & Sake Evening',
    description:
      'Intimate sushi dinner prepared by a Tokyo-trained chef. Experience traditional Japanese flavors and learn about sake pairing.',
    location: 'Paris, France',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    host: {
      id: 'h4',
      name: 'Kenji Tanaka',
      avatar: '/images/hosts/kenji.jpg',
      verified: true,
      languages: ['English', 'Japanese', 'French'],
    },
    cuisine: 'Japanese',
    cuisineIcon: '🍣',
    menu_description: 'Omakase-style sushi with premium sake selection',
    dietary_info: ['Gluten-free soy sauce available'],
    event_date: getRandomDate(15),
    event_time: '7:30 PM',
    event_remain_spots: 2,
    max_guests: 6,
    duration: '2 hours',
    price: 68,
    currency: 'EUR',
    includes: ['8-course omakase', 'Sake pairing', 'Miso soup', 'Green tea'],
    rating: 5.0,
    reviews: 89,
    featured: true,
    image: '/images/experiences/sushi-sake.jpg',
    images: ['/images/experiences/sushi-1.jpg', '/images/experiences/sushi-2.jpg'],
    tags: ['Premium', 'Romantic', 'Small group'],
    instant_book: false,
    isFavorited: false,
  },
  {
    id: '5',
    name: 'Mexican Fiesta Night',
    description:
      'Celebrate with authentic Mexican flavors! From handmade tortillas to mole sauce, experience the real taste of Mexico.',
    location: 'Barcelona, Spain',
    coordinates: { lat: 41.3851, lng: 2.1734 },
    host: {
      id: 'h5',
      name: 'Carmen Rodriguez',
      avatar: '/images/hosts/carmen.jpg',
      verified: true,
      languages: ['English', 'Spanish'],
    },
    cuisine: 'Mexican',
    cuisineIcon: '🌮',
    menu_description: 'Tacos, enchiladas, guacamole, and traditional desserts',
    dietary_info: ['Vegetarian options', 'Vegan options', 'Spice level adjustable'],
    event_date: getRandomDate(18),
    event_time: '7:00 PM',
    event_remain_spots: 8,
    max_guests: 12,
    duration: '3 hours',
    price: 35,
    currency: 'EUR',
    includes: ['Full Mexican feast', 'Margaritas', 'Churros', 'Live music'],
    rating: 4.7,
    reviews: 203,
    featured: false,
    image: '/images/experiences/restaurant-dining.jpg',
    images: [
      '/images/experiences/mexican-1.jpg',
      '/images/experiences/mexican-2.jpg',
      '/images/experiences/mexican-3.jpg',
    ],
    tags: ['Party atmosphere', 'Family-friendly', 'Vegetarian-friendly'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '6',
    name: 'Thai Street Food Journey',
    description:
      'Experience the vibrant flavors of Bangkok street food prepared in our home kitchen with family recipes.',
    location: 'London, UK',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    host: {
      id: 'h6',
      name: 'Somchai Wong',
      avatar: '/images/hosts/somchai.jpg',
      verified: true,
      languages: ['English', 'Thai'],
    },
    cuisine: 'Thai',
    cuisineIcon: '🍜',
    menu_description: 'Pad thai, green curry, spring rolls, and mango sticky rice',
    dietary_info: ['Vegetarian options', 'Vegan options', 'Nut allergy accommodated'],
    event_date: getRandomDate(20),
    event_time: '6:30 PM',
    event_remain_spots: 4,
    max_guests: 8,
    duration: '2.5 hours',
    price: 40,
    currency: 'EUR',
    includes: ['4-course meal', 'Thai iced tea', 'Recipe cards'],
    rating: 4.85,
    reviews: 142,
    featured: false,
    image: '/images/experiences/vietnamese-pho.jpg',
    images: ['/images/experiences/thai-1.jpg', '/images/experiences/thai-2.jpg'],
    tags: ['Authentic', 'Spicy', 'Family-friendly'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '7',
    name: 'French Bistro Classics',
    description:
      'Intimate French dining experience featuring classic bistro dishes prepared with local ingredients.',
    location: 'Paris, France',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    host: {
      id: 'h7',
      name: 'Pierre Dubois',
      avatar: '/images/hosts/pierre.jpg',
      verified: true,
      languages: ['English', 'French'],
    },
    cuisine: 'French',
    cuisineIcon: '🥐',
    menu_description: 'Coq au vin, ratatouille, cheese course, and crème brûlée',
    dietary_info: ['Vegetarian option for main course'],
    event_date: getRandomDate(22),
    event_time: '8:00 PM',
    event_remain_spots: 3,
    max_guests: 6,
    duration: '3 hours',
    price: 72,
    currency: 'EUR',
    includes: ['4-course meal', 'Wine pairing', 'Cheese course', 'Digestif'],
    rating: 4.92,
    reviews: 78,
    featured: true,
    image: '/images/experiences/french-bistro.jpg',
    images: ['/images/experiences/french-1.jpg', '/images/experiences/french-2.jpg'],
    tags: ['Romantic', 'Wine pairing', 'Traditional'],
    instant_book: false,
    isFavorited: false,
  },
  {
    id: '8',
    name: 'Spanish Tapas Evening',
    description:
      'Experience the Spanish tradition of tapas with a variety of small plates and conversation.',
    location: 'Madrid, Spain',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    host: {
      id: 'h8',
      name: 'Isabella Garcia',
      avatar: '/images/hosts/isabella.jpg',
      verified: true,
      languages: ['English', 'Spanish'],
    },
    cuisine: 'Spanish',
    cuisineIcon: '🥘',
    menu_description: 'Variety of tapas including patatas bravas, gambas, and tortilla',
    dietary_info: ['Vegetarian options', 'Gluten-free options'],
    event_date: getRandomDate(25),
    event_time: '7:00 PM',
    event_remain_spots: 6,
    max_guests: 10,
    duration: '2.5 hours',
    price: 38,
    currency: 'EUR',
    includes: ['8-10 tapas', 'Sangria', 'Spanish wine', 'Dessert'],
    rating: 4.75,
    reviews: 168,
    featured: false,
    image: '/images/experiences/italian-pasta.jpg',
    images: [
      '/images/experiences/spanish-1.jpg',
      '/images/experiences/spanish-2.jpg',
      '/images/experiences/spanish-3.jpg',
    ],
    tags: ['Social', 'Family-friendly', 'Wine included'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '9',
    name: 'Moroccan Feast Under the Stars',
    description:
      'Experience Moroccan hospitality with a traditional feast served on our rooftop terrace.',
    location: 'Barcelona, Spain',
    coordinates: { lat: 41.3851, lng: 2.1734 },
    host: {
      id: 'h9',
      name: 'Fatima Hassan',
      avatar: '/images/hosts/fatima.jpg',
      verified: true,
      languages: ['English', 'Arabic', 'Spanish'],
    },
    cuisine: 'Moroccan',
    cuisineIcon: '🫕',
    menu_description: 'Tagine, couscous, bastilla, and mint tea ceremony',
    dietary_info: ['Vegetarian options', 'Halal'],
    event_date: getRandomDate(28),
    event_time: '7:30 PM',
    event_remain_spots: 7,
    max_guests: 12,
    duration: '3 hours',
    price: 46,
    currency: 'EUR',
    includes: ['Full Moroccan feast', 'Mint tea ceremony', 'Traditional music', 'Rooftop setting'],
    rating: 4.88,
    reviews: 112,
    featured: true,
    image: '/images/experiences/restaurant-dining.jpg',
    images: [
      '/images/experiences/moroccan-1.jpg',
      '/images/experiences/moroccan-2.jpg',
      '/images/experiences/moroccan-3.jpg',
    ],
    tags: ['Outdoor', 'Traditional', 'Large groups welcome'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '10',
    name: 'Lebanese Mezze Experience',
    description:
      "Discover the flavors of Lebanon with an authentic mezze spread prepared by our grandmother's recipes.",
    location: 'London, UK',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    host: {
      id: 'h10',
      name: 'Layla Khoury',
      avatar: '/images/hosts/layla.jpg',
      verified: true,
      languages: ['English', 'Arabic'],
    },
    cuisine: 'Lebanese',
    cuisineIcon: '🧆',
    menu_description: 'Hummus, tabbouleh, falafel, kebabs, and baklava',
    dietary_info: ['Vegetarian options', 'Vegan options', 'Halal'],
    event_date: getRandomDate(30),
    event_time: '6:30 PM',
    event_remain_spots: 5,
    max_guests: 8,
    duration: '2.5 hours',
    price: 42,
    currency: 'EUR',
    includes: ['12+ mezze dishes', 'Arabic coffee', 'Baklava', 'Arak tasting'],
    rating: 4.9,
    reviews: 134,
    featured: false,
    image: '/images/experiences/french-bistro.jpg',
    images: ['/images/experiences/lebanese-1.jpg', '/images/experiences/lebanese-2.jpg'],
    tags: ['Vegetarian-friendly', 'Traditional', 'Mediterranean'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '11',
    name: 'Portuguese Seafood Dinner',
    description:
      'Fresh seafood prepared Portuguese-style with ocean views. Experience the flavors of the Atlantic.',
    location: 'Lisbon, Portugal',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    host: {
      id: 'h11',
      name: 'João Silva',
      avatar: '/images/hosts/joao.jpg',
      verified: true,
      languages: ['English', 'Portuguese'],
    },
    cuisine: 'Portuguese',
    cuisineIcon: '🦞',
    menu_description: 'Grilled fish, seafood rice, and pastéis de nata',
    dietary_info: ['Pescatarian', 'Gluten-free options'],
    event_date: getRandomDate(32),
    event_time: '7:00 PM',
    event_remain_spots: 4,
    max_guests: 8,
    duration: '2.5 hours',
    price: 55,
    currency: 'EUR',
    includes: ['Fresh seafood feast', 'Portuguese wine', 'Dessert', 'Port wine'],
    rating: 4.82,
    reviews: 96,
    featured: false,
    image: '/images/experiences/sushi-sake.jpg',
    images: ['/images/experiences/portuguese-1.jpg', '/images/experiences/portuguese-2.jpg'],
    tags: ['Seafood', 'Ocean view', 'Wine included'],
    instant_book: false,
    isFavorited: false,
  },
  {
    id: '12',
    name: 'Turkish Home Cooking',
    description:
      'Experience the warmth of Turkish hospitality with traditional home-cooked dishes and stories.',
    location: 'Berlin, Germany',
    coordinates: { lat: 52.52, lng: 13.405 },
    host: {
      id: 'h12',
      name: 'Ayşe Yılmaz',
      avatar: '/images/hosts/ayse.jpg',
      verified: true,
      languages: ['English', 'Turkish', 'German'],
    },
    cuisine: 'Turkish',
    cuisineIcon: '🫓',
    menu_description: 'Meze, kebabs, börek, and traditional Turkish coffee',
    dietary_info: ['Vegetarian options', 'Halal'],
    event_date: getRandomDate(35),
    event_time: '6:30 PM',
    event_remain_spots: 6,
    max_guests: 10,
    duration: '3 hours',
    price: 40,
    currency: 'EUR',
    includes: ['Full Turkish meal', 'Turkish tea & coffee', 'Baklava', 'Turkish delight'],
    rating: 4.87,
    reviews: 145,
    featured: false,
    image: '/images/experiences/italian-pasta.jpg',
    images: [
      '/images/experiences/turkish-1.jpg',
      '/images/experiences/turkish-2.jpg',
      '/images/experiences/turkish-3.jpg',
    ],
    tags: ['Family-friendly', 'Traditional', 'Cultural'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '13',
    name: 'Vietnamese Pho Workshop',
    description:
      'Learn the art of making authentic Vietnamese pho from scratch, then enjoy your creation.',
    location: 'Paris, France',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    host: {
      id: 'h13',
      name: 'Linh Nguyen',
      avatar: '/images/hosts/linh.jpg',
      verified: true,
      languages: ['English', 'Vietnamese', 'French'],
    },
    cuisine: 'Vietnamese',
    cuisineIcon: '🍲',
    menu_description: 'Traditional pho, spring rolls, and Vietnamese coffee',
    dietary_info: ['Vegetarian pho available', 'Gluten-free options'],
    event_date: getRandomDate(38),
    event_time: '6:00 PM',
    event_remain_spots: 5,
    max_guests: 8,
    duration: '3 hours',
    price: 44,
    currency: 'EUR',
    includes: ['Hands-on cooking', 'Full meal', 'Vietnamese coffee', 'Recipe booklet'],
    rating: 4.93,
    reviews: 107,
    featured: true,
    image: '/images/experiences/vietnamese-pho.jpg',
    images: ['/images/experiences/vietnamese-1.jpg', '/images/experiences/vietnamese-2.jpg'],
    tags: ['Hands-on', 'Authentic', 'Learning experience'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '14',
    name: 'Korean BBQ Night',
    description: 'Interactive Korean BBQ experience with traditional banchan and soju tasting.',
    location: 'Amsterdam, Netherlands',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    host: {
      id: 'h14',
      name: 'Min-jun Kim',
      avatar: '/images/hosts/minjun.jpg',
      verified: true,
      languages: ['English', 'Korean', 'Dutch'],
    },
    cuisine: 'Korean',
    cuisineIcon: '🥩',
    menu_description: 'Korean BBQ with various meats, banchan, and kimchi',
    dietary_info: ['Vegetarian options', 'Gluten-free soy sauce'],
    event_date: getRandomDate(40),
    event_time: '7:00 PM',
    event_remain_spots: 6,
    max_guests: 10,
    duration: '2.5 hours',
    price: 52,
    currency: 'EUR',
    includes: ['Korean BBQ', 'Multiple banchan', 'Soju tasting', 'Korean desserts'],
    rating: 4.86,
    reviews: 124,
    featured: false,
    image: '/images/experiences/sushi-sake.jpg',
    images: [
      '/images/experiences/korean-1.jpg',
      '/images/experiences/korean-2.jpg',
      '/images/experiences/korean-3.jpg',
    ],
    tags: ['Interactive', 'Social', 'Large groups welcome'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '15',
    name: 'Ethiopian Coffee Ceremony & Feast',
    description:
      'Experience traditional Ethiopian hospitality with injera, wat, and an authentic coffee ceremony.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h15',
      name: 'Selam Tadesse',
      avatar: '/images/hosts/selam.jpg',
      verified: true,
      languages: ['English', 'Amharic'],
    },
    cuisine: 'Ethiopian',
    cuisineIcon: '🫓',
    menu_description: 'Variety of wats served on injera with coffee ceremony',
    dietary_info: ['Vegetarian options', 'Vegan options', 'Gluten-free injera available'],
    event_date: getRandomDate(42),
    event_time: '6:30 PM',
    event_remain_spots: 7,
    max_guests: 10,
    duration: '3 hours',
    price: 38,
    currency: 'EUR',
    includes: ['Ethiopian feast', 'Coffee ceremony', 'Traditional bread', 'Cultural storytelling'],
    rating: 4.91,
    reviews: 89,
    featured: false,
    image: '/images/experiences/restaurant-dining.jpg',
    images: ['/images/experiences/ethiopian-1.jpg', '/images/experiences/ethiopian-2.jpg'],
    tags: ['Cultural', 'Vegetarian-friendly', 'Unique experience'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '16',
    name: 'Irish Traditional Supper',
    description:
      'Experience authentic Irish comfort food in a cozy Georgian home with stories and music.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h16',
      name: "Siobhán O'Brien",
      avatar: '/images/hosts/siobhan.jpg',
      verified: true,
      languages: ['English', 'Irish'],
    },
    cuisine: 'Irish',
    cuisineIcon: '🍀',
    menu_description: 'Irish stew, soda bread, colcannon, and apple tart',
    dietary_info: ['Vegetarian options', 'Gluten-free bread available'],
    event_date: getRandomDate(7),
    event_time: '6:30 PM',
    event_remain_spots: 4,
    max_guests: 8,
    duration: '2.5 hours',
    price: 48,
    currency: 'EUR',
    includes: ['3-course meal', 'Irish whiskey tasting', 'Traditional music', 'Tea & cake'],
    rating: 4.88,
    reviews: 156,
    featured: true,
    image: '/images/experiences/french-bistro.jpg',
    images: ['/images/experiences/irish-1.jpg', '/images/experiences/irish-2.jpg'],
    tags: ['Traditional', 'Cultural', 'Music'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '17',
    name: 'Modern Irish Tasting Menu',
    description:
      'Contemporary Irish cuisine showcasing local seasonal ingredients with a creative twist.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h17',
      name: 'Cian Murphy',
      avatar: '/images/hosts/cian.jpg',
      verified: true,
      languages: ['English'],
    },
    cuisine: 'Modern Irish',
    cuisineIcon: '🌿',
    menu_description: '5-course tasting menu with Irish craft beverages',
    dietary_info: ['Vegetarian menu available', 'Vegan options'],
    event_date: getRandomDate(10),
    event_time: '7:30 PM',
    event_remain_spots: 2,
    max_guests: 6,
    duration: '3 hours',
    price: 75,
    currency: 'EUR',
    includes: ['5 courses', 'Wine pairing', 'Amuse-bouche', 'Petit fours'],
    rating: 4.95,
    reviews: 78,
    featured: true,
    image: '/images/experiences/italian-pasta.jpg',
    images: ['/images/experiences/modern-1.jpg', '/images/experiences/modern-2.jpg'],
    tags: ['Premium', 'Fine dining', 'Local ingredients'],
    instant_book: false,
    isFavorited: false,
  },
  {
    id: '18',
    name: 'Dublin Brunch Experience',
    description: 'Late morning brunch featuring the best of Irish breakfast with a modern twist.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h18',
      name: 'Aoife Kelly',
      avatar: '/images/hosts/aoife.jpg',
      verified: true,
      languages: ['English'],
    },
    cuisine: 'Irish Brunch',
    cuisineIcon: '🍳',
    menu_description: 'Full Irish breakfast, eggs benedict, pastries, and mimosas',
    dietary_info: ['Vegetarian options', 'Gluten-free options'],
    event_date: getRandomDate(3),
    event_time: '11:00 AM',
    event_remain_spots: 6,
    max_guests: 10,
    duration: '2 hours',
    price: 35,
    currency: 'EUR',
    includes: ['Full brunch spread', 'Mimosas', 'Fresh juices', 'Coffee & tea'],
    rating: 4.82,
    reviews: 203,
    featured: false,
    image: '/images/experiences/restaurant-dining.jpg',
    images: ['/images/experiences/brunch-1.jpg', '/images/experiences/brunch-2.jpg'],
    tags: ['Weekend', 'Family-friendly', 'Late morning'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '19',
    name: 'Seafood by the Coast',
    description: 'Fresh Dublin Bay seafood prepared simply to let the natural flavors shine.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h19',
      name: 'Declan Walsh',
      avatar: '/images/hosts/declan.jpg',
      verified: true,
      languages: ['English'],
    },
    cuisine: 'Seafood',
    cuisineIcon: '🦐',
    menu_description: 'Oysters, Dublin Bay prawns, fish & chips, and seafood chowder',
    dietary_info: ['Pescatarian', 'Gluten-free options available'],
    event_date: getRandomDate(14),
    event_time: '7:00 PM',
    event_remain_spots: 3,
    max_guests: 8,
    duration: '2.5 hours',
    price: 58,
    currency: 'EUR',
    includes: ['Seafood feast', 'White wine', 'Dessert', 'Coffee'],
    rating: 4.79,
    reviews: 112,
    featured: false,
    image: '/images/experiences/sushi-sake.jpg',
    images: ['/images/experiences/seafood-1.jpg', '/images/experiences/seafood-2.jpg'],
    tags: ['Seafood', 'Fresh catch', 'Wine pairing'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '20',
    name: 'Persian Feast Night',
    description:
      'Discover the rich flavors of Persian cuisine with saffron rice, kebabs, and traditional stews.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h20',
      name: 'Maryam Tehrani',
      avatar: '/images/hosts/maryam.jpg',
      verified: true,
      languages: ['English', 'Farsi'],
    },
    cuisine: 'Persian',
    cuisineIcon: '🍚',
    menu_description: 'Tahdig, koobideh, ghormeh sabzi, and Persian sweets',
    dietary_info: ['Vegetarian options', 'Halal'],
    event_date: getRandomDate(16),
    event_time: '7:00 PM',
    event_remain_spots: 5,
    max_guests: 10,
    duration: '3 hours',
    price: 45,
    currency: 'EUR',
    includes: ['Full Persian meal', 'Persian tea', 'Saffron ice cream', 'Baklava'],
    rating: 4.92,
    reviews: 87,
    featured: false,
    image: '/images/experiences/vietnamese-pho.jpg',
    images: ['/images/experiences/persian-1.jpg', '/images/experiences/persian-2.jpg'],
    tags: ['Traditional', 'Halal', 'Cultural'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '21',
    name: 'Chinese Dumpling Workshop',
    description:
      'Learn to fold and cook authentic Chinese dumplings from scratch with a Sichuan chef.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h21',
      name: 'Wei Chen',
      avatar: '/images/hosts/wei.jpg',
      verified: true,
      languages: ['English', 'Mandarin'],
    },
    cuisine: 'Chinese',
    cuisineIcon: '🥟',
    menu_description: 'Handmade dumplings, spring rolls, and mapo tofu',
    dietary_info: ['Vegetarian options', 'Vegan dumplings available'],
    event_date: getRandomDate(19),
    event_time: '6:00 PM',
    event_remain_spots: 8,
    max_guests: 12,
    duration: '3 hours',
    price: 40,
    currency: 'EUR',
    includes: ['Hands-on cooking', 'Full meal', 'Chinese tea', 'Recipe cards'],
    rating: 4.85,
    reviews: 134,
    featured: false,
    image: '/images/experiences/sushi-sake.jpg',
    images: ['/images/experiences/chinese-1.jpg', '/images/experiences/chinese-2.jpg'],
    tags: ['Hands-on', 'Family-friendly', 'Learning'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '22',
    name: 'Spanish Paella Party',
    description: 'Watch and help prepare authentic Valencian paella cooked over an open fire.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h22',
      name: 'Carlos Fernandez',
      avatar: '/images/hosts/carlos.jpg',
      verified: true,
      languages: ['English', 'Spanish'],
    },
    cuisine: 'Spanish',
    cuisineIcon: '🥘',
    menu_description: 'Mixed paella, tapas selection, and churros with chocolate',
    dietary_info: ['Seafood paella', 'Vegetarian paella available'],
    event_date: getRandomDate(21),
    event_time: '6:30 PM',
    event_remain_spots: 10,
    max_guests: 14,
    duration: '3 hours',
    price: 42,
    currency: 'EUR',
    includes: ['Paella feast', 'Sangria', 'Tapas', 'Churros'],
    rating: 4.76,
    reviews: 189,
    featured: true,
    image: '/images/experiences/italian-pasta.jpg',
    images: ['/images/experiences/paella-1.jpg', '/images/experiences/paella-2.jpg'],
    tags: ['Social', 'Outdoor cooking', 'Large groups'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '23',
    name: 'Middle Eastern Mezze Night',
    description:
      'A vibrant evening of Middle Eastern flavors with homemade hummus, falafel, and shawarma.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h23',
      name: 'Omar Hassan',
      avatar: '/images/hosts/omar.jpg',
      verified: true,
      languages: ['English', 'Arabic'],
    },
    cuisine: 'Middle Eastern',
    cuisineIcon: '🧆',
    menu_description: 'Hummus, falafel, shawarma, tabbouleh, and baklava',
    dietary_info: ['Vegetarian options', 'Vegan options', 'Halal'],
    event_date: getRandomDate(23),
    event_time: '7:00 PM',
    event_remain_spots: 6,
    max_guests: 10,
    duration: '2.5 hours',
    price: 38,
    currency: 'EUR',
    includes: ['Full mezze spread', 'Mint tea', 'Baklava', 'Arabic coffee'],
    rating: 4.84,
    reviews: 98,
    featured: false,
    image: '/images/experiences/french-bistro.jpg',
    images: ['/images/experiences/me-1.jpg', '/images/experiences/me-2.jpg'],
    tags: ['Vegetarian-friendly', 'Halal', 'Social'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '24',
    name: 'Caribbean Jerk Chicken Experience',
    description:
      'Taste the Caribbean with authentic jerk chicken, rice & peas, and tropical cocktails.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h24',
      name: 'Marcus Thompson',
      avatar: '/images/hosts/marcus.jpg',
      verified: true,
      languages: ['English'],
    },
    cuisine: 'Caribbean',
    cuisineIcon: '🌴',
    menu_description: 'Jerk chicken, rice & peas, fried plantains, and rum punch',
    dietary_info: ['Gluten-free options', 'Spice level adjustable'],
    event_date: getRandomDate(26),
    event_time: '6:30 PM',
    event_remain_spots: 8,
    max_guests: 12,
    duration: '3 hours',
    price: 44,
    currency: 'EUR',
    includes: ['Full Caribbean feast', 'Rum punch', 'Tropical dessert', 'Reggae music'],
    rating: 4.78,
    reviews: 67,
    featured: false,
    image: '/images/experiences/restaurant-dining.jpg',
    images: ['/images/experiences/caribbean-1.jpg', '/images/experiences/caribbean-2.jpg'],
    tags: ['Party vibe', 'Music', 'Tropical'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '25',
    name: 'Polish Pierogi Workshop',
    description: 'Learn to make traditional Polish pierogi from scratch with a Polish grandmother.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h25',
      name: 'Anna Kowalski',
      avatar: '/images/hosts/anna.jpg',
      verified: true,
      languages: ['English', 'Polish'],
    },
    cuisine: 'Polish',
    cuisineIcon: '🥟',
    menu_description: 'Pierogi with various fillings, bigos, and Polish desserts',
    dietary_info: ['Vegetarian pierogi available'],
    event_date: getRandomDate(29),
    event_time: '5:00 PM',
    event_remain_spots: 4,
    max_guests: 8,
    duration: '3.5 hours',
    price: 36,
    currency: 'EUR',
    includes: ['Hands-on cooking', 'Full meal', 'Polish vodka tasting', 'Recipe booklet'],
    rating: 4.91,
    reviews: 54,
    featured: false,
    image: '/images/experiences/vietnamese-pho.jpg',
    images: ['/images/experiences/polish-1.jpg', '/images/experiences/polish-2.jpg'],
    tags: ['Hands-on', 'Traditional', 'Learning'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '26',
    name: 'Brazilian BBQ Churrasco',
    description:
      'Experience authentic Brazilian churrasco with endless grilled meats and caipirinha cocktails.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h26',
      name: 'Rafael Santos',
      avatar: '/images/hosts/rafael.jpg',
      verified: true,
      languages: ['English', 'Portuguese'],
    },
    cuisine: 'Brazilian',
    cuisineIcon: '🥩',
    menu_description: 'Picanha, linguiça, chicken hearts, feijoada, and brigadeiro',
    dietary_info: ['Meat-focused', 'Vegetarian sides available'],
    event_date: getRandomDate(31),
    event_time: '7:00 PM',
    event_remain_spots: 9,
    max_guests: 14,
    duration: '3 hours',
    price: 55,
    currency: 'EUR',
    includes: ['All-you-can-eat meats', 'Caipirinha', 'Sides buffet', 'Brazilian desserts'],
    rating: 4.87,
    reviews: 142,
    featured: true,
    image: '/images/experiences/restaurant-dining.jpg',
    images: ['/images/experiences/brazilian-1.jpg', '/images/experiences/brazilian-2.jpg'],
    tags: ['Meat lovers', 'Social', 'Large groups'],
    instant_book: true,
    isFavorited: false,
  },
  {
    id: '27',
    name: 'Portuguese Wine & Tapas',
    description:
      'Discover the wines of Portugal paired with traditional petiscos in an intimate setting.',
    location: 'Dublin, Ireland',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    host: {
      id: 'h27',
      name: 'Sofia Pereira',
      avatar: '/images/hosts/sofia.jpg',
      verified: true,
      languages: ['English', 'Portuguese'],
    },
    cuisine: 'Portuguese',
    cuisineIcon: '🍷',
    menu_description: 'Portuguese petiscos, cheeses, cured meats, and pastéis de nata',
    dietary_info: ['Vegetarian options', 'Pescatarian options'],
    event_date: getRandomDate(33),
    event_time: '7:30 PM',
    event_remain_spots: 3,
    max_guests: 6,
    duration: '2.5 hours',
    price: 52,
    currency: 'EUR',
    includes: ['5 wine tastings', 'Petiscos spread', 'Port wine', 'Dessert'],
    rating: 4.94,
    reviews: 76,
    featured: false,
    image: '/images/experiences/french-bistro.jpg',
    images: ['/images/experiences/port-1.jpg', '/images/experiences/port-2.jpg'],
    tags: ['Wine tasting', 'Romantic', 'Small group'],
    instant_book: false,
    isFavorited: false,
  },
]
